% Auto-generated by cameraCalibrator app on 09-Oct-2024
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\src\2425sspp\pract03\GoPro\gopro01.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro02.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro03.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro04.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro05.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro06.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro07.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro08.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro09.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro10.jpg',...
    'C:\src\2425sspp\pract03\GoPro\gopro11.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 50;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
